services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn pipeline.api.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: streamlit-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    plan: free
    envVars:
      - key: API_URL
        value: https://fastapi-backend.onrender.com
