name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run preprocessing tests
      run: pytest tests/test_processing.py

    - name: Run training tests
      run: pytest tests/test_training.py

    - name: Run prediction tests
      run: pytest tests/test_prediction.py

    - name: Run segmentation tests
      run: pytest tests/test_segmentation.py