name: MLOps Pipeline CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy pytest tqdm textblob
      - name: Run preprocessing tests
        run: pytest tests/test_processing.py

  training:
    runs-on: ubuntu-latest
    needs: preprocessing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy pytest mlflow joblib tensorflow xgboost transformers tf-keras
      - name: Run training tests
        run: pytest tests/test_training.py

  prediction:
    runs-on: ubuntu-latest
    needs: training
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy pytest mlflow joblib tensorflow xgboost transformers tf-keras
      - name: Run prediction tests
        run: pytest tests/test_prediction.py

  segmentation:
    runs-on: ubuntu-latest
    needs: prediction
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy pytest torch joblib transformers
      - name: Run segmentation tests
        run: pytest tests/test_segmentation.py

  deploy:
    runs-on: ubuntu-latest
    needs: [segmentation] # Waits for all previous jobs to succeed
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ismail004/mlops-pipeline:latest .
          docker push ismail004/mlops-pipeline:latest
