name: Scrape New Tweet

on:
  push:
    paths:
      - 'scraping/urls.txt'  # Ou urls.csv

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

    - name: Run scraper
      run: python scraping/main.py
